esphome:
  name: prusa1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  
mqtt:
  broker: 192.168.0.203
  port: 1883
  username: "admin"
  password: "admin"
  on_message:
    topic: prusa/mains
    qos: 0
    then:
      - delay: 30s
      - switch.turn_off: mains

captive_portal:

# Enable logging
logger:

ota:
  
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

switch:
  - platform: output
    name: mains
    id: mains
    output: relay_1
    
status_led:
  pin:
    number: GPIO13
    inverted: yes